export const cities = [
  { label: "New York, NY", value: "New York" },
  { label: "Los Angeles, CA", value: "Los Angeles" },
  { label: "Chicago, IL", value: "Chicago" },
  { label: "Houston, TX", value: "Houston" },
  { label: "Phoenix, AZ", value: "Phoenix" },
  { label: "Philadelphia, PA", value: "Philadelphia" },
  { label: "San Antonio, TX", value: "San Antonio" },
  { label: "San Diego, CA", value: "San Diego" },
  { label: "Dallas, TX", value: "Dallas" },
  { label: "San Jose, CA", value: "San Jose" },
  { label: "Austin, TX", value: "Austin" },
  { label: "Jacksonville, FL", value: "Jacksonville" },
  { label: "Fort Worth, TX", value: "Fort Worth" },
  { label: "Columbus, OH", value: "Columbus" },
  { label: "Charlotte, NC", value: "Charlotte" },
  { label: "Indianapolis, IN", value: "Indianapolis" },
  { label: "Seattle, WA", value: "Seattle" },
  { label: "Denver, CO", value: "Denver" },
  { label: "Washington, DC", value: "Washington" },
  { label: "Boston, MA", value: "Boston" },
  { label: "El Paso, TX", value: "El Paso" },
  { label: "Nashville, TN", value: "Nashville" },
  { label: "Detroit, MI", value: "Detroit" },
  { label: "Oklahoma City, OK", value: "Oklahoma City" },
  { label: "Portland, OR", value: "Portland" },
  { label: "Las Vegas, NV", value: "Las Vegas" },
  { label: "Memphis, TN", value: "Memphis" },
  { label: "Louisville, KY", value: "Louisville" },
  { label: "Baltimore, MD", value: "Baltimore" },
  { label: "Milwaukee, WI", value: "Milwaukee" },
  { label: "Albuquerque, NM", value: "Albuquerque" },
  { label: "Tucson, AZ", value: "Tucson" },
  { label: "Fresno, CA", value: "Fresno" },
  { label: "Sacramento, CA", value: "Sacramento" },
  { label: "Mesa, AZ", value: "Mesa" },
  { label: "Kansas City, MO", value: "Kansas City" },
  { label: "Atlanta, GA", value: "Atlanta" },
  { label: "Long Beach, CA", value: "Long Beach" },
  { label: "Omaha, NE", value: "Omaha" },
  { label: "Raleigh, NC", value: "Raleigh" },
  { label: "Miami, FL", value: "Miami" },
  { label: "Oakland, CA", value: "Oakland" },
  { label: "Minneapolis, MN", value: "Minneapolis" },
  { label: "Tulsa, OK", value: "Tulsa" },
  { label: "Bakersfield, CA", value: "Bakersfield" },
  { label: "Wichita, KS", value: "Wichita" },
  { label: "Cleveland, OH", value: "Cleveland" },
  { label: "Arlington, TX", value: "Arlington" },
  { label: "New Orleans, LA", value: "New Orleans" },
  { label: "Lansing, MI", value: "Lansing" },
  { label: "Chula Vista, CA", value: "Chula Vista" },
  { label: "Buffalo, NY", value: "Buffalo" },
  { label: "St. Louis, MO", value: "St. Louis" },
  { label: "Tampa, FL", value: "Tampa" },
  { label: "Corpus Christi, TX", value: "Corpus Christi" },
  { label: "Pittsburgh, PA", value: "Pittsburgh" },
  { label: "Riverside, CA", value: "Riverside" },
  { label: "Cincinnati, OH", value: "Cincinnati" },
  { label: "Anchorage, AK", value: "Anchorage" },
  { label: "Stockton, CA", value: "Stockton" },
  { label: "Toledo, OH", value: "Toledo" },
  { label: "Saint Paul, MN", value: "Saint Paul" },
  { label: "Henderson, NV", value: "Henderson" },
  { label: "Greensboro, NC", value: "Greensboro" },
  { label: "Plano, TX", value: "Plano" },
  { label: "Newark, NJ", value: "Newark" },
  { label: "Lincoln, NE", value: "Lincoln" },
  { label: "Orlando, FL", value: "Orlando" },
  { label: "Chandler, AZ", value: "Chandler" },
  { label: "Laredo, TX", value: "Laredo" },
  { label: "Durham, NC", value: "Durham" },
  { label: "Madison, WI", value: "Madison" },
  { label: "Gilbert, AZ", value: "Gilbert" },
  { label: "Hialeah, FL", value: "Hialeah" },
  { label: "Garland, TX", value: "Garland" },
  { label: "Irvine, CA", value: "Irvine" },
  { label: "Chesapeake, VA", value: "Chesapeake" },
  { label: "Irving, TX", value: "Irving" },
  { label: "Scottsdale, AZ", value: "Scottsdale" },
  { label: "North Las Vegas, NV", value: "North Las Vegas" },
  { label: "Fremont, CA", value: "Fremont" },
  { label: "Boise, ID", value: "Boise" },
  { label: "Richmond, VA", value: "Richmond" },
  { label: "Baton Rouge, LA", value: "Baton Rouge" },
  { label: "Des Moines, IA", value: "Des Moines" },
  { label: "Spokane, WA", value: "Spokane" },
  { label: "Glendale, AZ", value: "Glendale" },
  { label: "Reno, NV", value: "Reno" },
  { label: "Chattanooga, TN", value: "Chattanooga" },
  { label: "Denton, TX", value: "Denton" },
  { label: "Lubbock, TX", value: "Lubbock" },
  { label: "Akron, OH", value: "Akron" },
  { label: "Shreveport, LA", value: "Shreveport" },
  { label: "Tacoma, WA", value: "Tacoma" },
];
